### ISSUE TITLE
Volume control still can't control my bluetooth earbud

### ISSUE THREAD

**Issue by womeimingzi11** [JoniVR/MonitorControl#1]
I have upgrade my MonitorControl to latest version (1.3.1), as the release note shows:
> added a feature that automatically detects if monitor or other devices (for example AirPods) are being used and ignores volume control for other devices (meaning they can be controlled as they normally would by the system)

But it looks still can't control my bluetooth earbud (BeatsX) once I chose **Listen for Both Brightness & Volume**, as seeing from volume indictor of OSD, it still indicate the screen volume, how can I solve this?

BTW, my display is AOC LV243WUP, all the feature of ddcctl works well on it.

Thank you!

**Comment by JoniVR** [comment]
Hi @womeimingzi11 

It seems like I accidentally released version 1.3 under 1.3.1 releases on Github 🤦‍♂️ . 
I'll release the actual 1.3.1 in a few minutes, I'm sorry!

Kind regards,
Joni

**Comment by JoniVR** [comment]
Alright, I've fixed the release, could you try downloading version 1.3.1 again from the [releases](https://github.com/JoniVR/MonitorControl/releases) and let me know if it works now?

**Comment by womeimingzi11** [comment]
Cheers!

It works well with the new release.

Thanks for your work.

Have a nice day!

----------------------------------------------------

Chen Han
E-mail: chenhan14@lzu.edu.cn
School of Life Sciences, Lanzhou University, Lanzhou, 730000 P.R.China
在 2019年1月7日 +0800 PM6:57，Joni Van Roost <notifications@github.com>，写道：

**Comment by JoniVR** [comment]
I didn't do most of the work, I just fixed this up as it was very buggy for me and I really like the tool.
No problem, I'll double check the version next time 😉

You have a nice day too!
